### ISSUE TITLE
Fails to Install on OS X 10.11 with Error

### ISSUE THREAD

**Issue by paulie-g** [paulie-g/autopy2#45]
<a href="https://github.com/TaylorSMarks"><img src="https://avatars1.githubusercontent.com/u/4270526?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [TaylorSMarks](https://github.com/TaylorSMarks)**
_Thursday Jul 30, 2015 at 00:51 GMT_
_Originally opened as https://github.com/msanders/autopy/issues/75_

----

When I do

```
sudo pip install autopy
```

I fail with 10 warnings and 9 errors. The warnings are all about stuff that was deprecated in 10.6. The errors are as follows:

```
src/screengrab.c:194:15: error: use of undeclared identifier 'GL_FRONT'
            glReadBuffer(GL_FRONT);
                         ^

src/screengrab.c:199:22: error: use of undeclared identifier 'GL_NO_ERROR'
        if (glGetError() != GL_NO_ERROR) return NULL;
                            ^

src/screengrab.c:223:21: error: use of undeclared identifier 'GL_CLIENT_PIXEL_STORE_BIT'
        glPushClientAttrib(GL_CLIENT_PIXEL_STORE_BIT);
                           ^

src/screengrab.c:225:16: error: use of undeclared identifier 'GL_PACK_ALIGNMENT'
        glPixelStorei(GL_PACK_ALIGNMENT, BYTE_ALIGN); /* Force alignment. */
                      ^

src/screengrab.c:226:16: error: use of undeclared identifier 'GL_PACK_ROW_LENGTH'
        glPixelStorei(GL_PACK_ROW_LENGTH, 0);
                      ^

src/screengrab.c:227:16: error: use of undeclared identifier 'GL_PACK_SKIP_ROWS'
        glPixelStorei(GL_PACK_SKIP_ROWS, 0);
                      ^

src/screengrab.c:228:16: error: use of undeclared identifier 'GL_PACK_SKIP_PIXELS'
        glPixelStorei(GL_PACK_SKIP_PIXELS, 0);
                      ^

src/screengrab.c:236:30: error: use of undeclared identifier 'GL_BGRA'
                     MMRGB_IS_BGR ? GL_BGRA : GL_RGBA,
                                    ^

src/screengrab.c:240:15: error: use of undeclared identifier 'GL_UNSIGNED_INT_8_8_8_8_REV'
                     GL_UNSIGNED_INT_8_8_8_8_REV, /* Native format */
                     ^
```

**Comment by paulie-g** [comment]
<a href="https://github.com/elyase"><img src="https://avatars3.githubusercontent.com/u/1175888?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [elyase](https://github.com/elyase)**
_Thursday Jul 30, 2015 at 10:28 GMT_

----

I am getting this on 10.10 with the Anaconda python distribution.

**Comment by paulie-g** [comment]
<a href="https://github.com/elyase"><img src="https://avatars3.githubusercontent.com/u/1175888?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [elyase](https://github.com/elyase)**
_Thursday Jul 30, 2015 at 14:08 GMT_

----

Got it working on 10.11 with:

```
brew install libpng
CFLAGS="-Wno-return-type" pip install git+https://github.com/potpath/autopy.git
```

**Comment by paulie-g** [comment]
<a href="https://github.com/TaylorSMarks"><img src="https://avatars1.githubusercontent.com/u/4270526?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TaylorSMarks](https://github.com/TaylorSMarks)**
_Friday Jul 31, 2015 at 23:00 GMT_

----

I attempted to follow your directions, but I ended with this error:

```
src/png_io.c:3:10: fatal error: 'png.h' file not found
#include <png.h>
         ^
```

**Comment by paulie-g** [comment]
<a href="https://github.com/nuty"><img src="https://avatars1.githubusercontent.com/u/2208400?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nuty](https://github.com/nuty)**
_Thursday Nov 19, 2015 at 05:11 GMT_

----

@elyase  it worked,  thank you.
